// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaukXbBWogXfnEOY2Rd9KI8UXq7GohBAY',
    appId: '1:451138635293:web:166f8d724912679d2aa8f4',
    messagingSenderId: '451138635293',
    projectId: 'field-manger-30232',
    authDomain: 'field-manger-30232.firebaseapp.com',
    storageBucket: 'field-manger-30232.firebasestorage.app',
    measurementId: 'G-D46KZVQ3KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPGLilx-b1ZlBEIE8dztv34Wup6jgOC10',
    appId: '1:451138635293:android:d6d01ecd4915fc982aa8f4',
    messagingSenderId: '451138635293',
    projectId: 'field-manger-30232',
    storageBucket: 'field-manger-30232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFK1Jh2bXY1fvW5OKqpjREpM5LIlVj4O8',
    appId: '1:451138635293:ios:30976c58411524d02aa8f4',
    messagingSenderId: '451138635293',
    projectId: 'field-manger-30232',
    storageBucket: 'field-manger-30232.firebasestorage.app',
    iosBundleId: 'com.webentix.trackkaro',
  );

}